function ResultsPanel({ summary, questions, onClear }) {
  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text).then(() => {
      alert('Copied to clipboard!');
    }).catch(() => {
      alert('Failed to copy to clipboard');
    });
  };

  const exportResults = () => {
    const content = `SUMMERIFY Results
===================

SUMMARY:
${summary}

GENERATED QUESTIONS:
${questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

Generated by SUMMERIFY - AI Text Summarization Tool
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summerify-results-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="results-panel">
      <div className="results-header">
        <h2>Results</h2>
        <div className="results-actions">
          <button onClick={exportResults} className="action-button export">
            📥 Export
          </button>
          <button onClick={onClear} className="action-button clear">
            🗑️ Clear
          </button>
        </div>
      </div>

      {summary && (
        <div className="result-section">
          <div className="section-header">
            <h3>📝 Summary</h3>
            <button 
              onClick={() => copyToClipboard(summary)}
              className="copy-button"
              title="Copy summary"
            >
              📋
            </button>
          </div>
          <div className="summary-content">
            <p>{summary}</p>
          </div>
        </div>
      )}

      {questions.length > 0 && (
        <div className="result-section">
          <div className="section-header">
            <h3>❓ Generated Questions</h3>
            <button 
              onClick={() => copyToClipboard(questions.join('\n'))}
              className="copy-button"
              title="Copy all questions"
            >
              📋
            </button>
          </div>
          <div className="questions-content">
            <ol>
              {questions.map((question, index) => (
                <li key={index} className="question-item">
                  {question}
                </li>
              ))}
            </ol>
          </div>
        </div>
      )}
    </div>
  );
}

export default ResultsPanel;